config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]
  resources :categories do
    resources :products
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | HelloWater</title>
  </head>
  <body>    
    <h1>About</h1>
      <p>
        This is the first social network without any actual 
        social signs of it. This is just a testing WebApp. Nothing to
        see here.. Really..
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  If you have any questions, feel free to write to me
  this is my Email: pechtim@gmail.com. If you want a faster respond,
  just try to contact me via vk.com:
  <a href="https://vk.com/aliaspechtim">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>My Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to the HelloWater social media!</h1>

  <h2>
    You can start your new life here!
  </h2>
  
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<!-- Thumb-Slider-Element ends -->
<% end %>