config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]
  resources :categories do
    resources :products
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  self.per_page = 10
  has_many :products, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user, only: [:index]
  before_action :admin_user, only: [:create, :destroy]
  
  
  #Создание новой категории
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "New category added"
      redirect_to @category
    else
      render 'new'
    end
  end
  
  #Показ категории
  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page])
    redirect_to category_products_path(params[:id])
  end
  
  def new
    if !current_user.admin?
      redirect_to(categories_url)
    else
      @category = Category.new
    end
  end
  
  def index
    @categories = Category.paginate(page: params[:page])
  end
  
  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category and all the products within it were deleted"
    redirect_to categories_url
  end
  
    private
    
      def category_params
        params.require(:category).permit(:name)
      end
      
      def admin_user
        redirect_to(root_url) unless current_user.admin?
      end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  
  def current_category
    @current_category ||= Category.find_by(id: params[:category_id])
  end
  
end

app/views/categories/_category.html.erb
<li>
  <%= link_to category.name, category %>
  <% if current_user.admin? %>
    | <%= link_to "delete", category, method: :delete, class: "btn btn-sm btn-danger",
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/categories/index.html.erb
<% provide(:title, 'All categories') %>
<h1>All categories</h1>

<%= will_paginate %>

<ul class="categories">
  <%= render @categories %>
</ul>

<%= will_paginate %>

<% if current_user.admin? %>
  <%= link_to "Create new category", new_category_url , class: "btn btn-primary" %>
<% end %>

app/views/categories/new.html.erb
<% provide(:title, 'New Category') %>
<% provide(:button_text, 'Create new category') %>

<h1>Category create</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= render 'shared/category_form' %>
  
  </div>
</div>

app/views/categories/show.html.erb
<% provide(:title, current_category) %>
<h1>Hi</h1>

<%= will_paginate %>

<ul class="products">
  <%= render @products %>
</ul>

<%= will_paginate %>

<%= link_to "Create new product", new_category_product , class: "btn btn-primary" %>