config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :microposts,          only: [:create, :destroy]
  resources :categories do
    resources :products
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  self.per_page = 15
  belongs_to :category
  validates :name,        presence: true
  validates :category_id, presence: true
  validates :description, presence: true
  validates :size,        presence: true, length: { maximum: 100 }
  
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user, only: [:index]
  before_action :admin_user, only: [:create, :destroy]
  
  def new
    if !current_user.admin?
      redirect_to(categories_url)
    else
      @product = Product.new
    end
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def index
    @category = Category.find(params[:category_id])
    @products = @category.products.paginate(page: params[:page])
  end
  
  def create
    @product = current_category.products.build(product_params)
    if @product.save
      flash[:success] = "Product added!"
      redirect_to category_products_url(@current_category)
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:success] = "Product deleted"
    redirect_to request.referrer || categories_url(@current_category)
  end
  
  private
    def product_params
      params.require(:product).permit(:name, :size, :description)
    end
    
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<li id="product-<%= product.id %>">
  <span class="category"><%= link_to product.name, category_product_path(params[:category_id],product) %>
  <% if current_user.admin? %>
    | <%= link_to "delete", category_product_path(params[:category_id],product), method: :delete, class: "btn btn-sm btn-danger",
                                  data: { confirm: "You sure?" } %>
  <% end %>
  </span>
</li>

app/views/products/index.html.erb
<% provide(:title, current_category.name) %>
<h1>
  <%= @current_category.name %>
</h1>

<div class="container">  
  <% if current_category.products.any? %>
      <h3>Products (<%= @current_category.products.count %>)</h3>
      <%= will_paginate %>
      
      <ul class="products">
        <%= render @products %>
      </ul>
      <%= will_paginate %>
  <% end %>
</div>

<% if current_user.admin? %>
  <%= link_to "Create new product", new_category_product_url , class: "btn btn-primary" %>
<% end %>

app/views/products/new.html.erb
<% provide(:title, 'New Product') %>
<% provide(:button_text, 'Create new product') %>

<h1>Product create</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= render 'shared/product_form' %>
  
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>

<h1>
  <%= @product.name %>
</h1>
<div class = "container">
  <div class = "micropost">
    <h3><%= @product.size %></h3>
    <h3><%= @product.description %></h3>
  </div>
</div>